---
version: "2.4"
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORDS=yes
      - MARIADB_ROOT_PASSWORD=p@ssword
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress

  pmg-woocommerce-server:
    build: .
    environment:
      - DATABASE_HOST=mariadb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /var/log/nginx
      - /opt
    depends_on:
      - mariadb
    restart: always
    healthcheck:
      test: ["CMD", "ansible-playbook", "upstart.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s

