---
version: "2.4"
services:
  pmg-woocommerce-server:
    image: woocommerce
    #build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /var/log/nginx
      - /opt
    restart: always
