---
version: "2.4"
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_PASSWORD=p@ssword
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
    ports:
      - "3306:3306"
    networks:
      - wordpress

  woocommerce-server:
    build: .
    environment:
      - DATABASE_HOST=mariadb
      - URL=https://127.0.0.1
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - wordpress

    healthcheck:
      test: ["CMD", "ansible-playbook", "upstart.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  wordpress: