---
- name: Install woocommerce server
  hosts: localhost
  connection: local
  vars_files:
    - vars/prod.yml
  tasks:
    - name: Install Wordpress Dependencies
      include_tasks:
        file: jobs/build/install_dependencies.yml
        apply:
          tags:
          - nginx
          - php
          - build
      tags:
      - nginx
      - php
      - build

    - name: Install Wordpress
      include_tasks:
        file: jobs/build/install_wordpress.yml
        apply:
          tags:
          - wordpress
          - build
      tags:
        - wordpress
        - build

    - name: Install Plugins
      include_tasks:
        file: jobs/build/install_plugins.yml
        apply:
          tags:
          - plugins
          - build
      tags:
      - plugins
      - build

    - name: Generate SSL certificate
      include_tasks:
        file: jobs/run/sslcertificate_generate.yml
        apply:
          tags:
          - sslcertificate
          - run
      tags:
      - sslcertificate
      - run

    - name: Configure NGINX
      include_tasks:
        file: jobs/run/config_nginx.yml
        apply:
          tags:
          - nginx
          - run
      tags:
      - nginx
      - run

    - name: Configure Wordpress
      include_tasks:
        file: jobs/run/config_wp.yml
        apply:
          tags:
          - wordpress_config
          - run
      tags:
      - wordpress_config
      - run

    - name: Run nginx
      include_tasks:
        file: jobs/exec/run_nginx.yml
        apply:
          tags:
          - nginx
          - exec
      tags:
      - nginx
      - exec

    - name: Test Nginx
      include_tasks:
        file: jobs/tests/nginx_test.yml
        apply:
          tags:
          - nginx
          - test
          - run
      tags:
      - nginx
      - test
      - run

    - name: Test database connectivity
      include_tasks:
        file: jobs/tests/database_test.yml
        apply:
          tags:
          - database
          - test
          - run
      tags:
      - database
      - test
      - run

    - name: Test URL
      include_tasks:
        file: jobs/tests/wordpress_test.yml
        apply:
          tags:
          - url
          - test
          - run
      tags:
      - url
      - test
      - run









