---
- name: Install WooCommerce
  hosts: 127.0.0.1
  become: yes
  connection: local
  vars_files: vars/variables.yml
  tasks:
    - name: Install Wordpress Dependencies
      include_tasks:
        file: jobs/install/install_dependencies.yml
        apply:
          tags:
          - nginx
          - php
      tags:
      - nginx
      - php

    - name: Generate SSL certificate
      include_tasks:
        file: sslcertificate_generate.yml
        apply:
          tags:
          - sslcertificate

      tags:
      - sslcertificate



    - name: Configure NGINX
      include_tasks:
        file: jobs/config/config_nginx.yml
        apply:
          tags:
          - nginx
      tags:
      - nginx

    - name: Test Nginx
      include_tasks:
        file: jobs/tests/nginx_test.yml
        apply:
          tags:
          - nginx
          - tests
      tags:
      - nginx
      - test

    - name: Install Wordpress
      include_tasks:
        file: jobs/install/install_wordpress.yml
        apply:
          tags:
          - wordpress
      tags:
        - wordpress

    - name: Configure Wordpress
      include_tasks:
        file: jobs/config/config_wp.yml
        apply:
          tags:
          - wordpress
      tags:
      - wordpress

    - name: Install Plugins
      include_tasks:
        file: jobs/install/install_plugins.yml
        apply:
          tags:
          - plugins
      tags:
      - plugins

    - name: Test database connectivity
      include_tasks:
        file: jobs/tests/database_test.yml
        apply:
          tags:
          - database
          - test
      tags:
      - database
      - test

    - name: Test URL
      include_tasks:
        file: jobs/tests/wordpress_test.yml
        apply:
          tags:
          - url
          - test
      tags:
      - url
      - test









