---
- name: Install WooCommerce
  hosts: 127.0.0.1
  become: yes
  connection: local
  vars_files: vars/variables.yml
  tasks:
    - name: Install Wordpress Dependencies
      include_tasks:
        file: jobs/install/install_dependencies.yml

    - name: Test Nginx
      include_tasks:
        file: jobs/tests/nginx_test.yml
        tags:
          - nginx
          - tests
        apply:
          tags:
          - nginx
          - tests

    - name: Install Wordpress
      include_tasks: jobs/install/install_wordpress.yml

    - name: Install Plugins
      include_tasks: jobs/install/install_plugins.yml

    - name: Configure Wordpress
      include_tasks: jobs/config/config_wp.yml

    - name: Configure NGINX
      include_tasks: jobs/config/config_nginx.yml




