---
run:
  user: ptg-user

app:
  title: "{{ lookup('ansible.builtin.env', 'APP_TILE') }}"
  link: "{{ lookup('ansible.builtin.env', 'APP_LINK') }}"
  version: "{{ lookup('ansible.builtin.env', 'APP_VERSION') }}"

woocommerce:
  link: "{{ lookup('ansible.builtin.env', 'WOOCOMMERCE_LINK') }}"

theme_function: "/opt/wordpress/wp-content/themes/twentytwentyone/functions.php"

database:
  name: "{{ lookup('env', 'DATABASE_NAME') }}"
  user: "{{ lookup('env', 'DATABASE_USER') }}"
  password: "{{ lookup('env', 'DATABASE_PASSWORD') }}"
  host: "{{ lookup('env', 'DATABASE_HOST') }}"
  port: "{{ lookup('env', 'DATABASE_PORT') }}"

user:
  name: "{{ lookup('env', 'USER_NAME') }}"
  password: "{{ lookup('env', 'USER_PASSWORD') }}"
  email: "{{ lookup('env', 'USER_EMAIL') }}"

url: "{{ lookup('env', 'URL') }}"

organization:
  name: "{{ lookup('env', 'ORGANIZATION_NAME') }}"
  country: "{{ lookup('env', 'ORGANIZATION_COUNTRY') }}"
  email: "{{ lookup('env', 'ORGANIZATION_EMAIL') }}"
  hostname: "{{ lookup('env', 'ORGANISATION_HOSTNAME') }}"

cpu_count: "{{ lookup('env', 'CPU_COUNT') }}"

file_limit: "{{ lookup('env', 'FILE_LIMIT') }}"


ssl_key: "{{ lookup('env', 'SSL_KEY') }}"
ssl_cert: "{{ lookup('env', 'SSL_CERTIFICATE') }}"

ports:
  - 80
  - 443