---
run:
  user: ptg-user

app:
  title: "{{ lookup('ansible.builtin.env', 'APP_TILE') }}"
  link: "{{ lookup('ansible.builtin.env', 'APP_LINK') }}"
  version: "{{ lookup('ansible.builtin.env', 'APP_VERSION') }}"

woocommerce:
  link: "{{ lookup('ansible.builtin.env', 'WOOCOMMERCE_LINK') }}"

database:
  name: "{{ lookup('env', 'DATABASE_NAME') }}"
  user: "{{ lookup('env', 'DATABASE_USER') }}"
  password: "{{ lookup('env', 'DATABASE_PASSWORD') }}"
  host: "{{ lookup('env', 'DATABASE_HOST') }}"
  port: "{{ lookup('env', 'DATABASE_PORT') }}"

server_address: "{{ lookup('env', 'SERVER_ADDRESS') }}"

organization:
  name: "{{ lookup('env', 'ORGANIZATION_NAME') }}"
  country: "{{ lookup('env', 'ORGANIZATION_COUNTRY') }}"
  email: "{{ lookup('env', 'ORGANIZATION_EMAIL') }}"
  hostname: "{{ lookup('env', 'ORGANISATION_HOSTNAME') }}"

cpu_count: "{{ lookup('env', 'CPU_COUNT') }}"

file_limit: "{{ lookup('env', 'FILE_LIMIT') }}"

ports:
  http: "{{ lookup('env', 'HTTP_PORT') }}"
  https: "{{ lookup('env', 'HTTPS_PORT') }}"

ssl_cert: "{{ lookup('env', ''SSL_CERT) }}"

protocol: "{{ lookup('env', 'PROTOCOL') }}"

ports_test:
  - 8080
  - 8443
