---
- name: Delete wp-sample-config.php
  file:
    path: /opt/wordpress/wp-config-sample.php
    state: absent

- name: Template nginx config file to /opt/wordpress/wp-config.php
  template:
    src: templates/wp-config.j2
    dest: /opt/wordpress/wp-config.php
