---
- name: Create a directory for caching
  file:
    path: /home/wp_cache
    state: directory

- name: Delete file nginx.conf
  file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: Template nginx config file to /etc/nginx/nginx.conf
  template:
    src: templates/nginx.j2
    dest: /etc/nginx/nginx.conf

- name: Delete file fasstcgi_params
  file:
    path: /etc/nginx/fastcgi_params
    state: absent

- name: Template fastcgi_params file to etc/nginx/nginx.conf
  template:
    src: templates/fastcgi_params.j2
    dest: /etc/nginx/fastcgi_params

- name: Remove default file /etc/nginx/sites-available/default
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Remove default file /etc/nginx/sites-enabled/default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Template a file to /etc/nginx/sites-available
  template:
    src: templates/wpsite.j2
    dest: /etc/nginx/sites-enabled/"{{ organization.hostname }}"

- name: Template a file to etc/nginx/sites-enabled
  template:
    src: templates/wpsite.j2
    dest: /etc/nginx/sites-enabled/"{{ organization.hostname }}"



