---
- name: Delete wp-sample-config.php
  file:
    path: /opt/wordpress/wp-config-sample.php
    state: absent

- name: Template nginx config file to /opt/wordpress/wp-config.php
  template:
    src: templates/wp-config.j2
    dest: /opt/wordpress/wp-config.php

- name: Add codeblock to file /opt/wordpress/wp-content/themes/twentytwentyone/functions.php to Pre-install admin user
  blockinfile:
    path: "{{ theme_function }}"
    content: |
     /*
     * Create an admin user add programmatically
     */
     add_action('init', 'xyz1234_my_custom_add_user');
     function xyz1234_my_custom_add_user() {
         $username = '{{ user.name}}';
         //set usename as per preference
         $password = '{{ user.password }}';
         //set password as per preference
         $email = '{{ user.email }}}';
         //set email as per preference
         if (username_exists($username) == null && email_exists($email) == false) {
             // Create the new user
             $user_id = wp_create_user($username, $password, $email);
             // Get current user object
             $user = get_user_by('id', $user_id);
             // Remove role
             $user->remove_role('subscriber');
             // Add role
             $user->add_role('administrator');
         }
     }
