---
- name: Configure nginx .conf
  template:
    src: /opt/manager/templates/nginx.j2
    dest: /etc/nginx/nginx.conf
    force: yes

- name: Configure nginx http webserver
  template:
    src: /opt/manager/templates/wpsite_http.j2
    dest: /etc/nginx/conf.d/wpsite_http.conf
    force: yes
  when: protocol == "http"

- name: Configure nginx https webserver
  template:
    src: /opt/manager/templates/wpsite_https.j2
    dest: /etc/nginx/conf.d/wpsite_https.conf
    force: yes
  when: protocol == "https"

