---
- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "/etc/ssl/private/{{ organization.hostname }}.com.pem"
    backup: yes

- name: Generate an OpenSSL Certificate Signing Request with Subject information
  openssl_csr:
    path:  "/etc/ssl/certs/{{ organization.name }}.com.crt"
    privatekey_path: "/etc/ssl/private/{{ organization.hostname }}.com.pem"
    country_name: "{{ organization.country }}"
    organization_name: "{{ organization.name }}"
    email_address: "{{ organization.email }}"
    common_name: "{{ organization.hostname }}"